/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config
         * @description Return the current config/orbis.yaml as a dict. Drawer UI
         *     consumes this to populate the settings form.
         */
        get: operations["get_config_api_config_get"];
        put?: never;
        /**
         * Put Config
         * @description Apply a shallow-merge patch to config/orbis.yaml. Returns the
         *     normalized post-write config. Reloads the in-memory persona so
         *     the next voice session uses the new values.
         *
         *     Body shape is a partial config::
         *
         *         {"persona": {"name": "Atlas"}}              # rename
         *         {"voice": {"tts_backend": "elevenlabs"}}    # swap provider
         *         {"orb": {"variant": "nebula", "palette": "Helios"}}   # paid
         *
         *     ``persona`` + ``voice`` blocks are always editable. The ``orb``
         *     block requires the paid customization unlock — requests with an
         *     ``orb`` block while the caller lacks the entitlement return 403.
         *     Starter-orb selection happens via /api/orb/select_starter and is
         *     always allowed (restricted to the curated pool).
         *
         *     Drops unknown keys with a warning. Raises 400 on typed failures
         *     (invalid tts_backend, non-numeric temperature, etc.).
         */
        post: operations["put_config_api_config_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/delegates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Delegates Endpoint
         * @description Return the raw delegate entries from disk + each one's runtime
         *     parse state. The UI uses ``configured`` (registry-side) to flag
         *     entries that fail parse (e.g. missing required fields, bad type)
         *     so they can show inline.
         */
        get: operations["list_delegates_endpoint_api_delegates_get"];
        put?: never;
        /**
         * Create Delegate Endpoint
         * @description Add a new delegate. 409 if the name already exists — the UI's
         *     edit flow goes through PUT instead. Triggers a registry reload on
         *     success so the new delegate is dispatchable immediately.
         */
        post: operations["create_delegate_endpoint_api_delegates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/delegates/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reload Delegates Endpoint
         * @description Re-read config/delegates.yaml from disk.
         *
         *     Safe mid-session — delegate lookup happens per `delegate_to()` call,
         *     so in-flight sessions see the new registry on their next dispatch.
         */
        post: operations["reload_delegates_endpoint_api_delegates_reload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/delegates/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Delegate Endpoint
         * @description Reachability probe for a delegate config — used by the Settings
         *     panel's "Test" button so users can verify before saving.
         *
         *     Accepts the same body shape as POST/PUT. For ``a2a`` the probe is
         *     a GET against ``/.well-known/agent-card.json``; for ``openai`` it's
         *     a single-shot ``/chat/completions`` ping (mirrors /api/llm/test).
         *     Returns ``{ok, latency_ms?, error?}``. Auth-gated like other /api
         *     routes.
         */
        post: operations["test_delegate_endpoint_api_delegates_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/delegates/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Delegate Endpoint
         * @description Replace an existing delegate. 404 if the name doesn't exist.
         *     Body's ``name`` field must match the path param — guards against
         *     a careless rename via the wrong verb (use DELETE+POST for renames
         *     so the registry sees both lifecycle events).
         */
        put: operations["update_delegate_endpoint_api_delegates__name__put"];
        post?: never;
        /**
         * Delete Delegate Endpoint
         * @description Remove a delegate by name. 404 if the name doesn't exist.
         */
        delete: operations["delete_delegate_endpoint_api_delegates__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entitlement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Entitlement
         * @description Return the owner's current entitlement state — used by the UI
         *     to gate paid-tier features (customization editor, variant picker).
         */
        get: operations["get_entitlement_api_entitlement_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entitlement/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Checkout
         * @description Create a Stripe Checkout Session for the customization unlock.
         *     Returns ``{"url": "<stripe-hosted checkout page>"}``. Client
         *     redirects the user there; success/cancel URLs come back via
         *     STRIPE_SUCCESS_URL / STRIPE_CANCEL_URL.
         */
        post: operations["create_checkout_api_entitlement_checkout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/detect_local": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Llm Detect Local
         * @description Parallel probe Ollama (:11434) + LM Studio (:1234) on localhost.
         *     Returns only the providers that responded — voice-first homelab
         *     users get a "we noticed your local Ollama" callout in the wizard.
         *
         *     Unauth — localhost detection before auth is set is the whole point.
         */
        get: operations["llm_detect_local_api_llm_detect_local_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/mlx/pull": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Llm Mlx Pull
         * @description Stream an MLX model download (via huggingface_hub) as SSE.
         *
         *     Frontend equivalent of ``/api/llm/pull`` but for the MLX path —
         *     when the wizard's user picks the Built-in (MLX) preset, this
         *     endpoint downloads the chosen ``mlx-community/...`` repo into
         *     the HF cache directly so the first voice session doesn't pay
         *     the multi-GB download cost. Emits ``data: {status, completed,
         *     total}`` progress events while the download runs, then a final
         *     ``event: done``.
         *
         *     Body: ``{"model": "mlx-community/gemma-3n-E2B-it-4bit"}``
         *
         *     Unauth — same rationale as ``/api/llm/detect_local``.
         */
        post: operations["llm_mlx_pull_api_llm_mlx_pull_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Llm Models
         * @description GET /models against a configured URL + API key. Returns
         *     ``{ok, models[], error?}``. Populates the wizard's model combobox.
         *
         *     Unauth, same rationale as /api/llm/test.
         */
        post: operations["llm_models_api_llm_models_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/pull": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Llm Pull
         * @description Stream an Ollama pull as Server-Sent Events.
         *
         *     The wizard calls this when a user picks Ollama and the
         *     recommended model isn't installed yet — instead of asking them
         *     to drop into a terminal and run ``ollama pull <name>``, we
         *     proxy Ollama's native ``/api/pull`` and forward each NDJSON
         *     progress chunk as an SSE message. The frontend renders a
         *     progress bar from the ``completed`` / ``total`` fields.
         *
         *     Body::
         *
         *         {"name": "gemma3n:e2b", "url": "http://127.0.0.1:11434"}
         *
         *     The ``url`` defaults to the local Ollama instance; we trim any
         *     trailing ``/v1`` so the same value used as ``llm.url`` for the
         *     OpenAI-compat endpoint also works here.
         *
         *     Unauth — same rationale as ``/api/llm/detect_local``: this runs
         *     before the wizard has set up an API key. URL is constrained by
         *     ``_ollama_url_is_safe`` so the route can't be turned into an
         *     SSRF gadget.
         */
        post: operations["llm_pull_api_llm_pull_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Llm Test
         * @description Real round-trip ping against a configured LLM endpoint.
         *
         *     Body: ``{url, model, api_key?}``. Returns ``{ok, latency_ms?,
         *     error?, status?}``. Unauth on purpose — the setup wizard may run
         *     before the owner API key is set, and the user's LLM credentials
         *     are what's really being validated here, not their ORBIS auth.
         */
        post: operations["llm_test_api_llm_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_api_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/offer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Offer */
        post: operations["offer_api_offer_post"];
        delete?: never;
        options?: never;
        head?: never;
        /** Ice */
        patch: operations["ice_api_offer_patch"];
        trace?: never;
    };
    "/api/orb/select_starter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Select Starter
         * @description Commit a starter-orb pick to config/orbis.yaml. Called by the
         *     setup wizard after the user picks. Validates the slug against
         *     the pool, writes the orb block, reloads persona.
         *
         *     Body: ``{"slug": "<starter_slug>"}``.
         */
        post: operations["select_starter_api_orb_select_starter_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persona/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reload Persona Endpoint
         * @description Re-read config/orbis.yaml from disk.
         *
         *     Applied on the next voice session (persona is snapshotted at
         *     connect time). Returns the loaded persona's slug + name.
         */
        post: operations["reload_persona_endpoint_api_persona_reload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/personality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Personality
         * @description Return current personality state: axes + mood + recent drift
         *     events + session stats. Drives the drawer's Profile panel so the
         *     user can see why the orb feels a certain way.
         */
        get: operations["get_personality_api_personality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/starter_orbs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Starter Orbs
         * @description Return the curated starter-orb pool. The setup wizard calls this
         *     at first boot so the user can pick one; no auth required so the
         *     wizard can run before the user has their API key.
         *
         *     Response shape::
         *         {"starters": [{slug, name, description, variant, palette, params}, ...]}
         */
        get: operations["get_starter_orbs_api_starter_orbs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stripe/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stripe Webhook
         * @description Stripe webhook endpoint. Verified via signature header. NOT auth-
         *     gated — Stripe's webhook call doesn't carry our API key; the
         *     signature check is the authentication. Configure this URL in the
         *     Stripe dashboard + set STRIPE_WEBHOOK_SECRET in .env.
         */
        post: operations["stripe_webhook_api_stripe_webhook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tts/voices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tts Voices
         * @description Enumerate voices/references for a given TTS backend.
         *
         *     Settings-panel uses this to render a Select instead of asking the user
         *     to know voice IDs. Each entry is ``{id, label, ...}``; backends that
         *     cache voices on disk (kokoro) include a ``cached`` flag so the UI can
         *     distinguish "ready" from "downloads on first use".
         *
         *     Empty ``voices`` for a remote-managed backend (fish, elevenlabs) means
         *     the server is unreachable or has no references registered — surface
         *     a friendly "is the sidecar running?" hint in the UI rather than
         *     failing the panel.
         */
        get: operations["tts_voices_api_tts_voices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tts/voices/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tts Download Voice
         * @description Eagerly download a Kokoro voice tensor so the user doesn't pay
         *     the latency on the first synthesis turn after switching voices.
         *
         *     Body: ``{"backend": "kokoro", "voice": "<id>"}``. Returns
         *     ``{ok, path?, error?}``. Idempotent — re-downloading an already-
         *     cached voice no-ops via HF cache hit. Other backends (fish/openai/
         *     elevenlabs) don't have a "download" concept and respond with a
         *     descriptive error.
         */
        post: operations["tts_download_voice_api_tts_voices_download_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reload Users Endpoint
         * @description Re-fetch the user roster from Infisical (if configured) or the
         *     YAML file. Safe to call mid-session — active clients keep their
         *     authenticated state until they reconnect; new connections use the
         *     refreshed registry.
         */
        post: operations["reload_users_endpoint_api_users_reload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/verbosity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Verbosity */
        get: operations["get_verbosity_api_verbosity_get"];
        put?: never;
        /** Set Verbosity */
        post: operations["set_verbosity_api_verbosity_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voiceprint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Voiceprint Delete
         * @description Remove the cached voiceprint — gate falls back to owner-trust on
         *     the next session. Use to start a fresh enrollment from the drawer
         *     UI or via curl when the audio sample needs to be replaced.
         */
        delete: operations["voiceprint_delete_api_voiceprint_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voiceprint/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Voiceprint Enroll
         * @description Encode + save an enrollment recording. Body is raw WAV bytes.
         *
         *     Returns 200 with metadata on success, 4xx on validation, 501 if
         *     speechbrain isn't installed (bundled deployments can opt-in via
         *     ``pip install -e ".[speaker-id]"``).
         */
        post: operations["voiceprint_enroll_api_voiceprint_enroll_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voiceprint/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Voiceprint Status
         * @description Tells the wizard whether enrollment is needed.
         */
        get: operations["voiceprint_status_api_voiceprint_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Whoami
         * @description Return the resolved owner. Clients call this at boot to confirm
         *     their API key is valid and get the display name for UI chrome.
         */
        get: operations["whoami_api_whoami_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Public — no auth. Reports process-wide shape, not per-user state.
         */
        get: operations["health_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IceCandidate
         * @description The remote ice candidate object received from the peer connection.
         *
         *     Parameters:
         *         candidate: The ice candidate patch SDP string (Session Description Protocol).
         *         sdp_mid: The SDP mid for the candidate patch.
         *         sdp_mline_index: The SDP mline index for the candidate patch.
         */
        IceCandidate: {
            /** Candidate */
            candidate: string;
            /** Sdp Mid */
            sdp_mid: string;
            /** Sdp Mline Index */
            sdp_mline_index: number;
        };
        /**
         * SmallWebRTCPatchRequest
         * @description Small WebRTC transport session arguments for the runner.
         *
         *     Parameters:
         *         pc_id: Identifier for the peer connection.
         *         candidates: A list of ICE candidate patches.
         */
        SmallWebRTCPatchRequest: {
            /** Candidates */
            candidates: components["schemas"]["IceCandidate"][];
            /** Pc Id */
            pc_id: string;
        };
        /**
         * SmallWebRTCRequest
         * @description Small WebRTC transport session arguments for the runner.
         *
         *     Parameters:
         *         sdp: The SDP string (Session Description Protocol).
         *         type: The type of the SDP, either "offer" or "answer".
         *         pc_id: Optional identifier for the peer connection.
         *         restart_pc: Optional whether to restart the peer connection.
         *         request_data: Optional custom data sent by the customer.
         */
        SmallWebRTCRequest: {
            /** Pc Id */
            pc_id?: string | null;
            /** Request Data */
            request_data?: unknown | null;
            /** Restart Pc */
            restart_pc?: boolean | null;
            /** Sdp */
            sdp: string;
            /** Type */
            type: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_config_api_config_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_config_api_config_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_delegates_endpoint_api_delegates_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_delegate_endpoint_api_delegates_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reload_delegates_endpoint_api_delegates_reload_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_delegate_endpoint_api_delegates_test_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_delegate_endpoint_api_delegates__name__put: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_delegate_endpoint_api_delegates__name__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_entitlement_api_entitlement_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_checkout_api_entitlement_checkout_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    llm_detect_local_api_llm_detect_local_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    llm_mlx_pull_api_llm_mlx_pull_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    llm_models_api_llm_models_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    llm_pull_api_llm_pull_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    llm_test_api_llm_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_api_metrics_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    offer_api_offer_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SmallWebRTCRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ice_api_offer_patch: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SmallWebRTCPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    select_starter_api_orb_select_starter_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reload_persona_endpoint_api_persona_reload_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_personality_api_personality_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_starter_orbs_api_starter_orbs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    stripe_webhook_api_stripe_webhook_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    tts_voices_api_tts_voices_get: {
        parameters: {
            query?: {
                backend?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tts_download_voice_api_tts_voices_download_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reload_users_endpoint_api_users_reload_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_verbosity_api_verbosity_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_verbosity_api_verbosity_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    voiceprint_delete_api_voiceprint_delete: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    voiceprint_enroll_api_voiceprint_enroll_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    voiceprint_status_api_voiceprint_status_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whoami_api_whoami_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
