/**
 * Typed fetch wrappers for ORBIS's /api/* endpoints. These hit the
 * server through the same origin — Vite proxies in dev, real origin
 * in the deployed SPA. All calls attach the owner API key (when set)
 * as ``X-API-Key``.
 *
 * Endpoint paths are validated against the OpenAPI schema in
 * ``api-types.ts`` (regenerated by ``bun run codegen:api``). Removing
 * or renaming a route on the server breaks the frontend build at the
 * call site rather than at runtime — that's the drift gate.
 *
 * Response *types* are kept as hand-rolled interfaces below: most of
 * our handlers return plain dicts, so FastAPI's OpenAPI schema types
 * them as ``unknown`` and we'd lose specificity by switching over.
 */

import { authHeaders } from '@/auth/apiKey';
import type { paths } from './api-types';

// Endpoint paths from the OpenAPI schema, minus ones with templated
// segments like ``/api/delegates/{name}``. Templated paths are built
// via ``buildPath()`` so the call site still references a known
// template literal.
type StaticPath = Exclude<keyof paths, `${string}{${string}}${string}`>;
type TemplatedPath = Extract<keyof paths, `${string}{${string}}${string}`>;

// Allow a query-string suffix on any static path (TS treats template
// literals structurally — `/api/foo?x=1` matches `${StaticPath}?…`).
// `BuiltPath` is a branded string returned by buildPath() so the
// helpers can stay strict (no plain `string` allowed) while still
// accepting paths built from templated routes.
type BuiltPath = string & { readonly __orbisBuiltPath: unique symbol };
type EndpointPath = StaticPath | `${StaticPath}?${string}` | BuiltPath;

/** Substitute ``{name}`` style params in a known templated path. */
function buildPath<P extends TemplatedPath>(
  template: P,
  params: Record<string, string>,
): BuiltPath {
  const filled = template.replace(/\{(\w+)\}/g, (_m, k) => {
    const v = params[k];
    if (v === undefined) throw new Error(`buildPath: missing param "${k}" for ${template}`);
    return encodeURIComponent(v);
  });
  return filled as BuiltPath;
}

export type Verbosity = 'silent' | 'brief' | 'narrated' | 'chatty';
export type VerbosityResponse = { verbosity: Verbosity };

export type Whoami = {
  id: string;
  display_name: string;
  auth_source: 'infisical' | 'file' | 'empty';
};

export type StarterOrb = {
  slug: string;
  name: string;
  description: string;
  variant: string;
  palette: string;
  params: Record<string, unknown>;
};

export type StarterOrbsResponse = { starters: StarterOrb[] };

export type OrbisConfig = {
  persona?: {
    slug?: string;
    name?: string;
    user_name?: string;
    system_prompt?: string;
    system_prompt_file?: string;
    temperature?: number;
    max_tokens?: number;
    filler_verbosity?: Verbosity;
  };
  voice?: {
    tts_backend?: 'kokoro' | 'openai' | 'elevenlabs' | 'fish';
    voice?: string;
    // OpenAI-compat endpoint overrides — surface here so the UI can
    // edit a custom gateway (protoLabs, LocalAI, vLLM-omni) without
    // requiring an env edit + restart. Empty / undefined means fall
    // back to TTS_OPENAI_* env defaults at the server.
    tts_url?: string;
    tts_model?: string;
    tts_api_key?: string;
  };
  llm?: {
    url?: string;
    model?: string;
    api_key?: string;
    api_key_env?: string;
    extra_body?: Record<string, unknown> | null;
  };
  stt?: {
    backend?: 'local' | 'openai' | 'sensevoice';
    // HF model id used by the local Whisper backend. Honoured at boot
    // only — runtime changes log a warning and no-op until next start.
    whisper_model?: string;
    // OpenAI-compatible endpoint overrides — same lift pattern as the
    // TTS panel. Empty strings round-trip as None on the server.
    url?: string;
    model?: string;
    api_key?: string;
  };
  orb?: {
    variant?: string;
    palette?: string;
    params?: Record<string, unknown>;
    // Authoring deltas per voice state and mood dimension — see
    // DECISIONS.md (2026-04-23 amendment) and
    // web/src/plugins/orb/compose.ts for the composition math.
    // Values are additive (numbers) or replacement (strings like hex
    // colors). Absent entries compose to no-op.
    state_overrides?: Partial<
      Record<'idle' | 'listening' | 'thinking' | 'speaking',
        Record<string, number | string>>
    >;
    mood_overrides?: Partial<
      Record<'valence' | 'arousal' | 'guardedness',
        Record<string, number | string>>
    >;
  };
};

export type EntitlementState = {
  customization: { active: boolean; configured: boolean };
};

export type PersonalityAxis = {
  axis: string;
  value: number;
  updated_at: string;
};

export type Mood = {
  valence: number;
  arousal: number;
  guardedness: number;
  updated_at: string;
} | null;

export type PersonalityEvent = {
  axis: string;
  delta: number;
  reason: string;
  at: string;
};

export type PersonalityState = {
  axes: PersonalityAxis[];
  mood: Mood;
  recent_events: PersonalityEvent[];
  sessions: {
    count: number;
    last_ended_at: string | null;
  };
};

/** Thrown when a response carries HTTP 401 — signals the key is wrong/missing. */
export class UnauthorizedError extends Error {
  constructor(path: string) { super(`${path} → 401 unauthorized`); }
}

// Delegate registry types — matches agent/delegate_config_store.validate_entry.
// A2A and OpenAI delegates share the common fields; the type-specific
// fields are union members so TS narrows correctly when `type` is checked.
export interface DelegateA2A {
  name: string;
  type: 'a2a';
  description: string;
  url: string;
  auth?: { scheme?: 'apiKey' | 'bearer'; credentialsEnv?: string };
  headers?: Record<string, string>;
}

export interface DelegateOpenAI {
  name: string;
  type: 'openai';
  description: string;
  url: string;
  model: string;
  api_key_env?: string;
  system_prompt?: string;
  max_tokens?: number;
  temperature?: number;
}

export type Delegate = DelegateA2A | DelegateOpenAI;

// GET response augments each entry with a runtime parse flag so the UI
// can flag rows that were rejected by the registry (missing required
// fields, etc.).
export type DelegateWithStatus = Delegate & { configured: boolean };

export type DelegateTestResult = {
  ok: boolean;
  latency_ms?: number;
  error?: string;
  status?: number;
};

// /healthz delegate health snapshot — surfaced to the SPA so the
// drawer banner can flag delegates that have failed N consecutive
// background probes. `ok` is null until the first probe lands.
//
// `last_error` is intentionally omitted from /healthz responses (the
// route is unauth and the field can carry internal hostnames / URLs
// from probe failures). The auth-gated /api/delegates surface includes
// it for the Settings panel — that's a separate type.
export interface HealthDelegate {
  name: string;
  type: 'a2a' | 'openai';
  ok: boolean | null;
  latency_ms: number | null;
  last_checked: number | null;
  consecutive_failures: number;
}

export interface HealthResponse {
  status: string;
  delegates?: HealthDelegate[];
}


async function get<T>(path: EndpointPath): Promise<T> {
  const r = await fetch(path, { headers: authHeaders() });
  if (r.status === 401) throw new UnauthorizedError(path);
  if (!r.ok) throw new Error(`${path} → HTTP ${r.status}`);
  return r.json() as Promise<T>;
}

async function postJSON<T>(path: EndpointPath, body: unknown): Promise<T> {
  return _send<T>('POST', path, body);
}

async function putJSON<T>(path: EndpointPath, body: unknown): Promise<T> {
  return _send<T>('PUT', path, body);
}

async function del<T>(path: EndpointPath): Promise<T> {
  return _send<T>('DELETE', path);
}

async function _send<T>(method: string, path: EndpointPath, body?: unknown): Promise<T> {
  const init: RequestInit = {
    method,
    headers: body
      ? authHeaders({ 'Content-Type': 'application/json' })
      : authHeaders(),
  };
  if (body !== undefined) init.body = JSON.stringify(body);
  const r = await fetch(path, init);
  if (r.status === 401) throw new UnauthorizedError(path);
  // Non-2xx but with a JSON body — surface the server's error message
  // so the UI can render it inline rather than the generic "HTTP 400".
  if (!r.ok) {
    let detail = `HTTP ${r.status}`;
    try {
      const body = await r.json();
      if (body?.error) detail = String(body.error);
    } catch {
      // body wasn't JSON; keep the generic detail
    }
    throw new ApiError(`${path} → ${detail}`, r.status);
  }
  return r.json() as Promise<T>;
}

export class ApiError extends Error {
  readonly status: number;
  constructor(message: string, status: number) {
    super(message);
    this.status = status;
  }
}

export const api = {
  // /healthz is unauth on the server; we send the auth header anyway —
  // harmless for that route and saves a separate fetch helper.
  healthz: () => get<HealthResponse>('/healthz'),
  whoami: () => get<Whoami>('/api/whoami'),
  verbosity: () => get<VerbosityResponse>('/api/verbosity'),
  setVerbosity: (level: Verbosity) =>
    postJSON<{ verbosity?: Verbosity; error?: string }>('/api/verbosity', { level }),
  starterOrbs: () => get<StarterOrbsResponse>('/api/starter_orbs'),
  config: () => get<{ config: OrbisConfig }>('/api/config'),
  putConfig: (patch: OrbisConfig) =>
    postJSON<{ ok?: boolean; config?: OrbisConfig; persona?: string }>('/api/config', patch),
  entitlement: () => get<EntitlementState>('/api/entitlement'),
  createCheckout: () => postJSON<{ url: string }>('/api/entitlement/checkout', {}),
  personality: () => get<PersonalityState>('/api/personality'),
  selectStarter: (slug: string) =>
    postJSON<{ ok: boolean; starter: StarterOrb }>('/api/orb/select_starter', { slug }),

  // LLM-provider probing for the setup wizard. These routes are
  // unauth — the wizard runs before the owner key is set and what's
  // really being validated is the user's LLM credentials.
  llmTest: (body: { url: string; model: string; api_key?: string }) =>
    postJSON<{ ok: boolean; latency_ms?: number; error?: string; status?: number }>(
      '/api/llm/test', body,
    ),
  llmModels: (body: { url: string; api_key?: string }) =>
    postJSON<{ ok: boolean; models: string[]; error?: string }>(
      '/api/llm/models', body,
    ),
  llmDetectLocal: () =>
    get<Partial<Record<'ollama' | 'lm_studio', { url: string; models: string[] }>>>(
      '/api/llm/detect_local',
    ),

  // TTS voice/reference enumeration. Settings panel uses this on
  // backend-change to populate a Select instead of asking the user to
  // know voice IDs by string. Empty `voices` for fish/elevenlabs means
  // the sidecar is unreachable or has no references — UI degrades to
  // free-text input.
  ttsVoices: (backend: string) =>
    get<{
      backend: string;
      voices: Array<{ id: string; label: string; cached?: boolean }>;
      fish_url?: string;
      error?: string;
    }>(`/api/tts/voices?backend=${encodeURIComponent(backend)}`),
  ttsDownloadVoice: (body: { backend: string; voice: string }) =>
    postJSON<{ ok: boolean; path?: string; error?: string }>(
      '/api/tts/voices/download', body,
    ),

  // Delegates CRUD + reachability probe. Used by the Settings panel
  // to manage sub-agents the orb can route to via delegate_to without
  // hand-editing config/delegates.yaml.
  delegates: {
    list: () => get<{ delegates: DelegateWithStatus[] }>('/api/delegates'),
    create: (entry: Delegate) =>
      postJSON<{ ok: boolean; delegates: DelegateWithStatus[] }>(
        '/api/delegates', entry,
      ),
    update: (name: string, entry: Delegate) =>
      putJSON<{ ok: boolean; delegates: DelegateWithStatus[] }>(
        buildPath('/api/delegates/{name}', { name }), entry,
      ),
    remove: (name: string) =>
      del<{ ok: boolean; delegates: DelegateWithStatus[] }>(
        buildPath('/api/delegates/{name}', { name }),
      ),
    test: (entry: Delegate) =>
      postJSON<DelegateTestResult>('/api/delegates/test', entry),
  },
};
