// Moved to @orbis/orb-runtime (shared with the orb editor). Re-export
// shim so existing variant imports keep working. The tuning values
// themselves now live in packages/orb-runtime/src/constants.ts.
export {
  ENV_STAGE2,
  ENV_USER,
  ENV_BOT,
  DISP_ALPHA,
  NORM_FLOOR,
  NORM_CEIL,
  SPEAK_ENTER,
  SPEAK_EXIT,
  LISTEN_MIN_DWELL_MS,
  THINK_DWELL_MS,
  STATE_XFADE_MS,
  MAX_DELTA_S,
  ROTATION_SCALE,
  DRAG_VEL_MAX,
  BREATH_HZ_1,
  BREATH_HZ_2,
  BREATH_AMP,
  ZOOM_MIN,
  ZOOM_MAX,
  ZOOM_LERP,
  DRAG_DAMP,
  CLICK_DECAY,
  TWO_PI,
  TIME_WRAP,
  ROT_WRAP,
  DRAG_SENSITIVITY,
} from '@orbis/orb-runtime';
